version: '3.7'

services: 
  postgres:
      container_name: postgres
      image: postgres:12
      ports:
          - '5433:5432'
      environment: 
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'secret'
          POSTGRES_DB: 'blockbuster'
      volumes:
          - ./pgdocker/pgdata:/var/lib/postgresql/data
          - ./pgdocker/init:/docker-entrypoint-initdb.d/
          
    # docker-compose -f docker-compose.yml up
  
  dash:
    container_name: dash
    build: ./dashdocker
    volumes: 
      - ./dashdocker/slides:/app/dash
    ports:
      - 8050:8050
    depends_on:
      - postgres
    restart: on-failure
    links: 
        - postgres

    #networks:
    #  vpcbr:
    #    ipv4_address: 10.5.0.6

  jupyter:
    container_name: jupyter
    build: ./jupydocker
    volumes:
      - ./jupydocker/slides:/home/jupyter
    ports:
      - 8888:8888
    depends_on:
      - postgres
    links: 
        - postgres

    #networks:
     # vpcbr:
     #   ipv4_address: 10.5.0.7


#networks:
#  vpcbr:
#    driver: bridge
#    ipam:
#     config:
#      - subnet: 10.5.0.0/16
#         #gateway: 10.5.0.1